### ISSUE TITLE
Long "Last data" intervals on NodeMCU Monitor

### ISSUE THREAD

**Issue by fichtenweg** [MrPsi/NodeMCU-Wixel#17]
Hello MrPsi,

I followed your guide as best as possible but I ended up with MCUNode-Wixel getting data very occasionally. When my son is in the same room with the NodeMCU I would expect to see Last Data not greater than 5 or 10 mins . In fact it is more common to see hours in the Last Data column than minutes. I think the Wixel is working fine since it starts to blink every 5 mins and then stops which means the signal is captured.

I configured the list of receivers on the xDrip app also including the mongo string with db and collection name. After performing fw update on the NodeMCU and uploading all needed files I saw the message "connected". Monitor shows green flag "available" so far everything should be fine, still I am not sure if data is captured and passed on to mongodb. Maybe I am missing something.

I configured list of receivers on another phone with xDrip+ app (no BT configuration) so as to check how many WiFi packets are getting transmitted from the NodeMCU-Wixel and found out that Last Data period is absolutely correct since I was able to see one single value 1h and 15 mins old while Last Data was showing 75 mins.

![image](https://cloud.githubusercontent.com/assets/10168739/24331531/bcb87e3c-123e-11e7-99e3-bd510e9f3e4f.png)

**Comment by MrPsi** [comment]
Hi,

It seems like you have done everything correctly because you get data occasionally.

But your problem can be related to any number of issues.
It could be bad contact in a soldering.
It could be a bad wifi connection.
It could be a broken circuit.

You can start debugging by connecting the usb cable from the NodeMCU to a computer and using Esplorer to connect to the NodeMCU and look at the debug prints. To see debug prints you need to set allowPrint = true in modStart.lua and re-upload it to the NodeMCU.
When debug prints are enabled, each time a reading is received by the Wixel it will be printed. Then you can see if the NodeMCU receives the data from the Wixel or not. If it doesn't, then it might be the connection between the Wixel and the NodeMCU.

You can also see each time a client (the monitor or a phone with xDrip) connects to the NodeMCU to get data. If you don't get those connections every five minutes it might be that the wifi connection is bad.

Start by trying what I suggested and see what you find out.

**Comment by fichtenweg** [comment]
Hi,

Thanks for responding. 

I checked the contacts, although they seemed ok under magnifying glass, I re-soldered them to be on the safe side. I really doubt a bad WiFi connection would be the root cause since the test location of the NodeMCU-Wixel is less than 1m away from the AP ( Linksys E2000 modified with 2 external antennas).
Although I cannot fully exclude broken cable, I am betting on a non-circuit issue. During the tests I never touched anything. 

However I have some further observations:

- I didn't measure exactly the interval at which values are captured (since it is quite a long one), but I noticed that when I check the MCU monitor at a relative same morning time I see almost same "Last Data" periods. So I think that the Wixel is capturing every packet, but far not every packet is getting transmitted by the NodeMCU. In fact I think the NodeMCU is transmitting once every 2hrs or so. Is it possible that the NodeMCU has some sleep timer activated.

- Communication with NodeMCU via Esplorer or doing a FW update is only possible when NOT connected to Wixel. Is that normal? 

- I have tested the NodeMCU-Wixel WITHOUT the Optional LED circuit, which means no circuit between D1/GPIO5-GND. In this case I also noticed that the blue LED on the NodeMCU doesn't flash when I press RESET
When I soldered a circuit between D1/GPIO5-GND the blue LED on the NodeMCU started to flash when pressing RESET, but still no communication via Esplorer was possible or FW update

**Comment by MrPsi** [comment]
Hi,

There are no sleep timer, you should be able to connect to the NodeMCU any time over wifi.

The LED circuit should't affect the usage. 

You should be able to communicate with the NodeMCU even though the Wixel is connected. Could it be that your USB port cannot provide enough current to power both the NodeMCU and the Wixel? You could try to power the Wixel with a separate usb cable.

I think the next step is to get the communication between ESplorer and the NodeMCU working, so you can debug the communication between the phone/monitor and the NodeMCU, and between the senor and NodeMCU.

**Comment by MrPsi** [comment]
Did you get it working?

**Comment by danpowell88** [comment]
If you dont wire the resistor in I was not able to communicate with the nodemcu without detaching the wixel.

There was a bug in a version of the wixel firmware to do with sleeping indefinitely when connected via usb i think, are you definitely using the latest?
